deepseek:
  api_key: "sk-40de98a818ff4a86bc92ed545ba63c24"
  api_url: "https://api.deepseek.com"
  
headers:
  User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"

crawler:
  espn_url: "https://www.espn.com/soccer/"
  football_italia_milan_url: "https://football-italia.net/category/teams/milan/"
